language: rust
rust:
  - stable
  - beta
  - nightly
cache:
  - apt
  - cargo
# needed for `cargo install cargo-travis`
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - cmake
    sources:
      - kalakris-cmake

os:
  - linux

matrix:
  allow_failures:
  - rust: beta
  - rust: nightly
  - os: osx

sudo: required

env:
  global:
    - RUST_BACKTRACE=1

branches:
  except:
    - test

notifications:
  irc:
    channels: "chat.freenode.net#zetox"
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} || Change view: %{compare_url}"
    on_success: change
    skip_join: true

before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]
    then
        ./scripts/verify-commit-messages.sh "$TRAVIS_COMMIT_RANGE" \
        && ./scripts/bootstrap-ubuntu-14-04.sh
    fi
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]
    then
        ./scripts/bootstrap-osx.sh
        export PKG_CONFIG_PATH=$HOME/installed_libsodium/lib/pkgconfig:$PKG_CONFIG_PATH
        export LD_LIBRARY_PATH=$HOME/installed_libsodium/lib:$LD_LIBRARY_PATH
    fi

script:
  - cargo build --verbose
  - cargo test --verbose
  - |
    if [[ "$TRAVIS_RUST_VERSION" == nightly ]]
    then
        cargo build --features "clippy" \
        && cargo test --features "clippy"
    fi
  - cargo doc

after_success:
  - >
    test $TRAVIS_PULL_REQUEST == "false"
    && (test $TRAVIS_BRANCH == "travis"
    || test $TRAVIS_BRANCH == "master" )
    && bash ./scripts/deploy-gh-pages.sh
  # measure code coverage and upload to coveralls.io
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]] && [[ "$TRAVIS_RUST_VERSION" == stable ]]
    then
      cargo install cargo-travis || echo "cargo-travis has been already installed"
      export PATH=$HOME/.cargo/bin:$PATH
      cargo coveralls
    fi
